name: Build images

on: 
  push:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/define-build-push.yml
    with:
      push_image: true
    secrets: inherit
